spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/mybatis_plus?useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456
mybatis-plus:
  type-aliases-package: com.example.mybatisPlus.pojo
  type-enums-package: com.example.mybatisPlus.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #id设置：雪花算法
  global-config:
    db-config:
      id-type: assign_id




